### ISSUE TITLE
e-Tag mismatch when disconnecting client 

### ISSUE THREAD

**Issue by galvesribeiro** [OrleansContrib/SignalR.Orleans#50]
@claylaut any idea why sometimes we get this exception when disconnecting a client:

```
fail: Orleans.Storage.MemoryGrainStorage[102203]
      Error from storage provider MemoryGrainStorage.Orleans.Streams.PubSubRendezvousGrain during WriteState for grain Type=Orleans.Streams.PubSubRendezvousGrain Pk=*grn/716E8E94/48ab3734bdcff7e7851b0115d917998506000000716e8e94+ORLEANS_SIGNALR_STREAM_PROVIDER_HW30mXWsyoehNkvu_O_trw-0x12A2E091 Id=GrainReference:*grn/716E8E94/d9179985+ORLEANS_SIGNALR_STREAM_PROVIDER_HW30mXWsyoehNkvu_O_trw Error=

      Exc level 0: Orleans.Storage.InconsistentStateException: e-Tag mismatch in Memory Storage. Stored = b73f9538df944e399cd961c55e175703 Received = f09d0617d36f44b7b01d3ca560cfe483
         at Orleans.Storage.MemoryGrainStorage.WriteStateAsync(String grainType, GrainReference grainReference, IGrainState grainState) in D:\build\agent2\_work\13\s\src\OrleansProviders\Storage\MemoryStorage.cs:line 101
         at Orleans.Core.StateStorageBridge`1.WriteStateAsync() in D:\build\agent2\_work\13\s\src\Orleans.Runtime\Storage\StateStorageBridge.cs:line 100
InconsistentStateException: e-Tag mismatch in Memory Storage. Stored = b73f9538df944e399cd961c55e175703 Received = f09d0617d36f44b7b01d3ca560cfe483 Expected Etag=b73f9538df944e399cd961c55e175703 Received Etag=f09d0617d36f44b7b01d3ca560cfe483
fail: Orleans.Streams.PubSubRendezvousGrain.S127.0.0.1:9000:270584380.*grn/716E8E94/48ab3734bdcff7e7851b0115d917998506000000716e8e94+ORLEANS_SIGNALR_STREAM_PROVIDER_HW30mXWsyoehNkvu_O_trw-0x12A2E091[103413]
      Failed to unregister a stream consumer.  Stream: HW30mXWsyoehNkvu_O_trw-bdcff7e7-3734-48ab-8599-17d915011b85-ORLEANS_SIGNALR_STREAM_PROVIDER, SubscriptionId 68a6a000-79a0-4cc0-8ab0-e28c83a9296b
InconsistentStateException: e-Tag mismatch in Memory Storage. Stored = b73f9538df944e399cd961c55e175703 Received = f09d0617d36f44b7b01d3ca560cfe483 Expected Etag=b73f9538df944e399cd961c55e175703 Received Etag=f09d0617d36f44b7b01d3ca560cfe483
```

**Comment by claylaut** [comment]
We used to have this issue when we used to write `State = null` and then write WriteStateAsync . 
Still, this seems coming from `PubSubRendezvousGrain` I had a quick peek to their code and they are using `ClearStateAsync` which reset to the default value which it could be setting it to `null`.

**Comment by galvesribeiro** [comment]
Fixed by 
https://github.com/dotnet/orleans/pull/5086
