### ISSUE TITLE
Extension not installed on grain

### ISSUE THREAD

**Issue by stephenlautier** [OrleansContrib/SignalR.Orleans#89]
I'm not entirely sure if something has changed or why is this happening. However, we recently are getting the following. Any ideas?

> Extension not installed on grain SignalR.Orleans.Groups.GroupGrain attempting to invoke type Orleans.Streams.OrleansCodeGenStreamConsumerExtensionMethodInvoker from invokable Orleans.Runtime.ActivationData

Source: **Orleans.Runtime**

Stacktrace: 
```
 at Orleans.Runtime.InsideRuntimeClient.Invoke(IAddressable target, IInvokable invokable, Message message)
   at Orleans.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask)
   at Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProducerExtension.StreamConsumerExtensionCollection.DeliverToRemote(IStreamConsumerExtension remoteConsumer, StreamId streamId, GuidId subscriptionId, Object item, Boolean optimizeForImmutableData, Boolean fireAndForgetDelivery)
   at Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProducer`1.OnNextAsync(T item, StreamSequenceToken token)
   at SignalR.Orleans.Clients.ClientGrain.OnDisconnect()
   at SignalR.Orleans.Clients.OrleansCodeGenClientGrainMethodInvoker.Invoke(IAddressable grain, InvokeMethodRequest request)
   at Orleans.Runtime.GrainMethodInvoker.Invoke()
   at Odin.Orleans.Logging.LoggingIncomingCallFilter.Invoke(IIncomingGrainCallContext context)
   at Orleans.Runtime.GrainMethodInvoker.Invoke()
   at Odin.Orleans.Error.UnknownErrorIncomingCallFilter.Invoke(IIncomingGrainCallContext context)
   at Orleans.Runtime.GrainMethodInvoker.Invoke()
   at Orleans.Runtime.InsideRuntimeClient.Invoke(IAddressable target, IInvokable invokable, Message message)
   at SignalR.Orleans.OrleansHubLifetimeManager`1.OnDisconnectedAsync(HubConnectionContext connection)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.OnConnectedAsync(ConnectionContext connection)
   at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher.ExecuteApplication(ConnectionDelegate connectionDelegate, HttpConnectionContext connection)
   at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext.WaitOnTasks(Task applicationTask, Task transportTask, Boolean closeGracefully)
   at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext.DisposeAsync(Boolean closeGracefully)
   at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager.DisposeAndRemoveAsync(HttpConnectionContext connection, Boolean closeGracefully)
```

**Comment by galvesribeiro** [comment]
THat is weird... Can you come down to gitter? would like to debug it...

**Comment by emilekberg** [comment]
It seems i've got the same issue. Did you ever find a solution to this? Exception seems to be the same as above, or very similar at least.

**Comment by stephenlautier** [comment]
@emilekberg Recently it seems ok.. few weeks ago we were still having it tho.

Last thing we've changed is, we updated to latest of this lib, but we are still on 2.3.5 orleans

**Comment by stephenlautier** [comment]
@emilekberg actually it seems it still happens, much less in frequency but it does happen

**Comment by digisimon** [comment]
Did you find a solution for this? I see the same exceptions unfortunately.

**Comment by stephenlautier** [comment]
@digisimon im glad that worked for you! We do have several fixes/improvements in our fork; we will need to contribute back to this at some point
